---
development:
  dialect: postgres
  database: anylogi
  user: timescaledb
  password: secret
  host: 127.0.0.1
  pool: 5
  port: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://timescaledb:secret@postgres:5432/anylogi_test?sslmode=disable"}}
