version: "3.3"
services:
  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: my-password
      POSTGRES_USER: postgres
      POSTGRES_DB: anylogi
    ports:
      - 5432:5439 # prevent conflict with local postgres server