version: "3.3"
services:
  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: anylogi
    ports:
      - 5432:5432 # prevent conflict with local postgres server