version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: anylogi