// Code generated by counterfeiter. DO NOT EDIT.
package walletfakes

import (
	"anylogibtc/domain/wallet"
	"anylogibtc/dto"
	"anylogibtc/entity"
	"context"
	"sync"
	"time"
)

type FakeTransactionRepository struct {
	HistoryStub        func(context.Context, time.Time, time.Time) ([]entity.Transaction, error)
	historyMutex       sync.RWMutex
	historyArgsForCall []struct {
		arg1 context.Context
		arg2 time.Time
		arg3 time.Time
	}
	historyReturns struct {
		result1 []entity.Transaction
		result2 error
	}
	historyReturnsOnCall map[int]struct {
		result1 []entity.Transaction
		result2 error
	}
	SendStub        func(context.Context, dto.TransactionDTO) error
	sendMutex       sync.RWMutex
	sendArgsForCall []struct {
		arg1 context.Context
		arg2 dto.TransactionDTO
	}
	sendReturns struct {
		result1 error
	}
	sendReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTransactionRepository) History(arg1 context.Context, arg2 time.Time, arg3 time.Time) ([]entity.Transaction, error) {
	fake.historyMutex.Lock()
	ret, specificReturn := fake.historyReturnsOnCall[len(fake.historyArgsForCall)]
	fake.historyArgsForCall = append(fake.historyArgsForCall, struct {
		arg1 context.Context
		arg2 time.Time
		arg3 time.Time
	}{arg1, arg2, arg3})
	stub := fake.HistoryStub
	fakeReturns := fake.historyReturns
	fake.recordInvocation("History", []interface{}{arg1, arg2, arg3})
	fake.historyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTransactionRepository) HistoryCallCount() int {
	fake.historyMutex.RLock()
	defer fake.historyMutex.RUnlock()
	return len(fake.historyArgsForCall)
}

func (fake *FakeTransactionRepository) HistoryCalls(stub func(context.Context, time.Time, time.Time) ([]entity.Transaction, error)) {
	fake.historyMutex.Lock()
	defer fake.historyMutex.Unlock()
	fake.HistoryStub = stub
}

func (fake *FakeTransactionRepository) HistoryArgsForCall(i int) (context.Context, time.Time, time.Time) {
	fake.historyMutex.RLock()
	defer fake.historyMutex.RUnlock()
	argsForCall := fake.historyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTransactionRepository) HistoryReturns(result1 []entity.Transaction, result2 error) {
	fake.historyMutex.Lock()
	defer fake.historyMutex.Unlock()
	fake.HistoryStub = nil
	fake.historyReturns = struct {
		result1 []entity.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionRepository) HistoryReturnsOnCall(i int, result1 []entity.Transaction, result2 error) {
	fake.historyMutex.Lock()
	defer fake.historyMutex.Unlock()
	fake.HistoryStub = nil
	if fake.historyReturnsOnCall == nil {
		fake.historyReturnsOnCall = make(map[int]struct {
			result1 []entity.Transaction
			result2 error
		})
	}
	fake.historyReturnsOnCall[i] = struct {
		result1 []entity.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeTransactionRepository) Send(arg1 context.Context, arg2 dto.TransactionDTO) error {
	fake.sendMutex.Lock()
	ret, specificReturn := fake.sendReturnsOnCall[len(fake.sendArgsForCall)]
	fake.sendArgsForCall = append(fake.sendArgsForCall, struct {
		arg1 context.Context
		arg2 dto.TransactionDTO
	}{arg1, arg2})
	stub := fake.SendStub
	fakeReturns := fake.sendReturns
	fake.recordInvocation("Send", []interface{}{arg1, arg2})
	fake.sendMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTransactionRepository) SendCallCount() int {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	return len(fake.sendArgsForCall)
}

func (fake *FakeTransactionRepository) SendCalls(stub func(context.Context, dto.TransactionDTO) error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = stub
}

func (fake *FakeTransactionRepository) SendArgsForCall(i int) (context.Context, dto.TransactionDTO) {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	argsForCall := fake.sendArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTransactionRepository) SendReturns(result1 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	fake.sendReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTransactionRepository) SendReturnsOnCall(i int, result1 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	if fake.sendReturnsOnCall == nil {
		fake.sendReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTransactionRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.historyMutex.RLock()
	defer fake.historyMutex.RUnlock()
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTransactionRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ wallet.TransactionRepository = new(FakeTransactionRepository)
