// Code generated by ent, DO NOT EDIT.

package ent

import (
	"anylogibtc/ent/predicate"
	"anylogibtc/ent/transaction"
	"anylogibtc/ent/wallet"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetAmount sets the "amount" field.
func (tu *TransactionUpdate) SetAmount(d decimal.Decimal) *TransactionUpdate {
	tu.mutation.ResetAmount()
	tu.mutation.SetAmount(d)
	return tu
}

// AddAmount adds d to the "amount" field.
func (tu *TransactionUpdate) AddAmount(d decimal.Decimal) *TransactionUpdate {
	tu.mutation.AddAmount(d)
	return tu
}

// SetSender sets the "sender" field.
func (tu *TransactionUpdate) SetSender(i int) *TransactionUpdate {
	tu.mutation.ResetSender()
	tu.mutation.SetSender(i)
	return tu
}

// AddSender adds i to the "sender" field.
func (tu *TransactionUpdate) AddSender(i int) *TransactionUpdate {
	tu.mutation.AddSender(i)
	return tu
}

// SetRecipient sets the "recipient" field.
func (tu *TransactionUpdate) SetRecipient(i int) *TransactionUpdate {
	tu.mutation.ResetRecipient()
	tu.mutation.SetRecipient(i)
	return tu
}

// AddRecipient adds i to the "recipient" field.
func (tu *TransactionUpdate) AddRecipient(i int) *TransactionUpdate {
	tu.mutation.AddRecipient(i)
	return tu
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (tu *TransactionUpdate) SetWalletID(id int) *TransactionUpdate {
	tu.mutation.SetWalletID(id)
	return tu
}

// SetNillableWalletID sets the "wallet" edge to the Wallet entity by ID if the given value is not nil.
func (tu *TransactionUpdate) SetNillableWalletID(id *int) *TransactionUpdate {
	if id != nil {
		tu = tu.SetWalletID(*id)
	}
	return tu
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (tu *TransactionUpdate) SetWallet(w *Wallet) *TransactionUpdate {
	return tu.SetWalletID(w.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (tu *TransactionUpdate) ClearWallet() *TransactionUpdate {
	tu.mutation.ClearWallet()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transaction.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.Sender(); ok {
		_spec.SetField(transaction.FieldSender, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedSender(); ok {
		_spec.AddField(transaction.FieldSender, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Recipient(); ok {
		_spec.SetField(transaction.FieldRecipient, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedRecipient(); ok {
		_spec.AddField(transaction.FieldRecipient, field.TypeInt, value)
	}
	if tu.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: wallet.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: wallet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetAmount sets the "amount" field.
func (tuo *TransactionUpdateOne) SetAmount(d decimal.Decimal) *TransactionUpdateOne {
	tuo.mutation.ResetAmount()
	tuo.mutation.SetAmount(d)
	return tuo
}

// AddAmount adds d to the "amount" field.
func (tuo *TransactionUpdateOne) AddAmount(d decimal.Decimal) *TransactionUpdateOne {
	tuo.mutation.AddAmount(d)
	return tuo
}

// SetSender sets the "sender" field.
func (tuo *TransactionUpdateOne) SetSender(i int) *TransactionUpdateOne {
	tuo.mutation.ResetSender()
	tuo.mutation.SetSender(i)
	return tuo
}

// AddSender adds i to the "sender" field.
func (tuo *TransactionUpdateOne) AddSender(i int) *TransactionUpdateOne {
	tuo.mutation.AddSender(i)
	return tuo
}

// SetRecipient sets the "recipient" field.
func (tuo *TransactionUpdateOne) SetRecipient(i int) *TransactionUpdateOne {
	tuo.mutation.ResetRecipient()
	tuo.mutation.SetRecipient(i)
	return tuo
}

// AddRecipient adds i to the "recipient" field.
func (tuo *TransactionUpdateOne) AddRecipient(i int) *TransactionUpdateOne {
	tuo.mutation.AddRecipient(i)
	return tuo
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (tuo *TransactionUpdateOne) SetWalletID(id int) *TransactionUpdateOne {
	tuo.mutation.SetWalletID(id)
	return tuo
}

// SetNillableWalletID sets the "wallet" edge to the Wallet entity by ID if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableWalletID(id *int) *TransactionUpdateOne {
	if id != nil {
		tuo = tuo.SetWalletID(*id)
	}
	return tuo
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (tuo *TransactionUpdateOne) SetWallet(w *Wallet) *TransactionUpdateOne {
	return tuo.SetWalletID(w.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (tuo *TransactionUpdateOne) ClearWallet() *TransactionUpdateOne {
	tuo.mutation.ClearWallet()
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	var (
		err  error
		node *Transaction
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Transaction)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TransactionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transaction.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.Sender(); ok {
		_spec.SetField(transaction.FieldSender, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedSender(); ok {
		_spec.AddField(transaction.FieldSender, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Recipient(); ok {
		_spec.SetField(transaction.FieldRecipient, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedRecipient(); ok {
		_spec.AddField(transaction.FieldRecipient, field.TypeInt, value)
	}
	if tuo.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: wallet.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: wallet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
